// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://comdhwqblqaofqrgmmrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvbWRod3FibHFhb2ZxcmdtbXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjQzNTgsImV4cCI6MjA1NjYwMDM1OH0.W1XmyfronyoS6cQvIjojLUxRrmaKY5Yo0Cas4qJFWBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);